apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: 
  labels:
    strimzi.io/cluster: 
  namespace: 
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
  topicName: 
