apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: 2.5.0
  connectCluster: 
  clusters:
  - alias: c1
    bootstrapServers: c1 
    tls: 
      trustedCertificates:
      - certificate: c1
        secretName: c1  
  - alias: c2
    bootstrapServers: c2 
    tls: 
      trustedCertificates:
      - certificate: c2
        secretName: c2    
  mirrors:
  - sourceCluster: 
    targetCluster:  
    sourceConnector: {}


